### ISSUE TITLE
Extension only shows a white page (maybe SSL related?)

### ISSUE THREAD

**Issue by lsfxz** [wallabag/chrome-ext#11]
Wallabag works as it should when regularly opened, but when trying to add a page using the extension I only get a blank square. If I'm logged in (regularly) at the same time the page gets added correctly, but this way I can't add tags right when bagging the page.

The extension works fine with demo.wallabag.org, so I guess it might have something to do with SSL: I've configured my server rather strictly: only TLS 1.2 is allowed, HSTS is used etc.

Unfortunately I don't know much about debugging browser extensions so right now I don't have much more than the SSL assumption.

![wall](https://cloud.githubusercontent.com/assets/13353732/9604258/b561a05a-50b6-11e5-895d-2fa9af951ea0.PNG)

(deactivating umatrix and ublock doesn't help, by the way)
(tried with different versions of chrome on different OSs)

**Comment by tcitworld** [comment]
> but this way I can't add tags right when bagging the page.

Yeah, sorry about that, we can't deliver this feature before wallabag server v2 is released, but that is under heavy work :)

> The extension works fine with demo.wallabag.org, so I guess it might have something to do with SSL: I've configured my server rather strictly: only TLS 1.2 is allowed, HSTS is used etc.

That's also what I think (http enforcing). Will investigate as soon as possible.

**Comment by lsfxz** [comment]
>>but this way I can't add tags right when bagging the page.

>Yeah, sorry about that, we can't deliver this feature before wallabag server v2 is released, but that is under heavy work :)

Oh — I thought it was already included and I was missing out.. well, I'm looking forward to that :)

> That's also what I think (http enforcing). Will investigate as soon as possible.

Thanks a ton.

**Comment by tcitworld** [comment]
>> but this way I can't add tags right when bagging the page.
> Oh — I thought it was already included and I was missing out.. well, I'm looking forward to that :)

Nope, that's only possible when you are on wallabag's interface itself atm.

**Comment by traxo-xx** [comment]
> > The extension works fine with demo.wallabag.org, so I guess it might have something to do with SSL: I've configured my server rather strictly: only TLS 1.2 is allowed, HSTS is used etc.

> That's also what I think (http enforcing). Will investigate as soon as possible.

I think I found the problem. I also have a rather strict webserver configuration, but the problem doesn't seem to be the ssl part of my config. A quick look into the chrome developer tools revealed this error message: `Refused to display '[Here was the URL of my installation]' in a frame because it set 'X-Frame-Options' to 'DENY'.`
And indeed removing that header from my nginx config did the trick.

Here's a related SO question:
http://stackoverflow.com/questions/15532791/getting-around-x-frame-options-deny-in-a-chrome-extension

**Comment by lsfxz** [comment]
That did indeed fix the issue for me as well. Thanks!
