### ISSUE TITLE
At last: Chrome plugin

### ISSUE THREAD

**Issue by nicosomb** [wallabag/chrome-ext#15]
_From @Rurik19 on May 27, 2016 11:40_
### Issue details

At last I finished the very first version of wallabag v2 plugin!

Here it is:
https://github.com/Rurik19/wallabagger

Would somebody test it? I doesn't want to publish it in store without approving of this community :)

_Copied from original issue: wallabag/wallabag#2120_

**Comment by nicosomb** [comment]
Wow thank you for this addon. 

Just tried: :+1: 

* I tried to add a tag, but it failed (with an existing tag, I've got undefined instead of the tag label. with an unexisting tag, it doesn't work)
* edit title :white_check_mark: 
* fav: just after saving the article it works. But when I click one more time on the wallabag icon of the addon, it doesn't work.
* mark as read : KO
* delete :white_check_mark: 

Good job!

**Comment by Rurik19** [comment]
1) how you finish adding tag: type , ; space enter? 
2) Existing tags must show while you typing to easy add by clicking on. Just some sort of autocomplete
3) fav: mean = setstarred - heart icon?

**Comment by nicosomb** [comment]
1. :+1: Nice it works. Need little explanation I think. In fact, when I add an existing tag and click on it, it fails.
2. :+1: 
3. yes

**Comment by nicosomb** [comment]
Wow I just saved an article with a preview picture :heart_eyes:

**Comment by Rurik19** [comment]
Tags "undefined " fixed. Also control of duplicate tags added.

**Comment by Rurik19** [comment]
Ok, I've published it in chrome webstore!
[wallabagger](https://chrome.google.com/webstore/detail/wallabagger/gbmgphmejlcoihgedabhgjdkcahacjlj)
